apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-svc
spec:
  ports:
  - name: nginx
    port: 80 # LB와 연결할 포트
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
